cp ~/.bash_aliases ./
cp ~/.config/kcminputrc ./
cp ~/.config/kglobalshortcutsrc ./
cp ~/.config/khotkeysrc ./
cp ~/.config/kxkbrc ./
cp ~/.config/plasma-localerc ./
cp ~/.config/powermanagementprofilesrc ./
cp ~/.config/plasma-org.kde.plasma.desktop-appletsrc ./
cp ~/networking.sh ./
cp ~/.config/dolphinrc ./
cp ~/.config/kwinrc ./
